# Server Configuration
server:
  port: 8080

spring:
  application:
    name: fcis-spring
  datasource:
    url: "${DATABASE_JDBC_URL}&reWriteBatchedInserts=true"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  flyway:
    enabled: true
